# Generated by Django 5.1.7 on 2025-03-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
